[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pip",
    "tenacity",
    "fastapi",
    "uvicorn",
    "google-genai",
    "docling",
    "markitdown",
    "crawl4ai",
    "pypdf>=5.4.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
